polo13999/nextAnt

package-lock.json, package.json
=> feature: add prettier formatter

.prettierignore, .prettierrc
=> Add prettier config

.eslintignore, .eslintrc, package-lock.json, package.json
=> add eslint

backend/index.js, backend/resolver/customer.js, backend/resolver/index.js, backend/schema/customer.js, backend/schema/index.js, pages/customer.js, src/components/customer/create-customer.js, src/components/customer/form.js, src/components/customer/index.js, src/components/nav/index.js, src/graphql/customer.js
=> can read and create customer

Dockerfile, README.md, package.json, pages/index.js, server.js, src/lib/initApollo.js, yarn.lock
add Dockfile and customer build  Apolloserver can't work problem
resolves #10
=> update dockfile and fix yarn start

backend/resolver/customer.js, backend/schema/customer.js, package.json, src/components/customer/create.js, src/components/customer/form.js, src/components/customer/index.js, src/components/customer/update.js, src/graphql/customer.js
=> can update/delete customer

.travis.yml, __test__/hello.test.js, package-lock.json, package.json, server.js
=> add jest test unit

backend/models/customer.js, backend/resolver/customer.js, config/ci.js, config/dev.js, config/keys.js, config/prod.js, package-lock.json, package.json, server.js, serverMiddle/apolloMiddle.js
=> add mongodb

Dockerfile, README.md, config/prod.js, package.json
resolves #41 
resolves #27 
resolves #39
resolves #22
=> dockerized our app

README.md
=> add live url to readme

client/.storybook/addons.js, client/.storybook/config.js, client/package-lock.json, client/package.json, client/src/components/nav/index.js, client/stories/nav.stories.js
=> add storybook

README.md
=> docs: add 3 stick

server/config/prod.js
=> fix: production cors error

client/src/components/layout/index.js, client/src/lib/checkLoggedIn.js
=> Show login picture

client/src/components/nav/index.js
=> Fix product icon

server/config/ci.js, server/config/dev.js, server/config/prod.js, server/index.js, server/src/utils.js
=> fix: cannt set cookie in production

client/src/components/nav/index.js, client/src/features/board/form.js, client/src/features/board/graphql.js, client/src/features/board/index.js, client/src/features/product/form.js, client/src/features/product/graphql.js, client/src/features/product/index.js, client/src/features/user/index.js, server/index.js, server/src/models/board.js, server/src/models/product.js, server/src/resolver/board.js, server/src/resolver/product.js, server/src/schema/board.js, server/src/schema/product.js
=> Connect mongo

client/src/features/board/form.js, client/src/features/board/index.js, client/src/features/customer/form.js, client/src/features/customer/index.js, client/src/features/product/form.js, client/src/features/product/index.js, server/src/resolver/board.js
when send Graphql the button will show loading effect
=> Loading effect

client/src/features/auth/login.js, client/src/features/auth/signup.js, client/src/features/board/index.js, client/src/features/product/index.js
ant design offer message just include it and use is ok
resolve #97
=> Global message

client/src/features/product/form.js, client/src/features/product/graphql.js, client/src/features/product/index.js, server/src/models/product.js, server/src/resolver/product.js, server/src/schema/product.js
add price and hide checkbox
fix display field 
resolve #111
=> add product field

client/package.json, client/pages/presonal/index.js, client/src/components/crudTemplate/modalBlock.js, client/src/components/crudTemplate/tableBlock.js, client/src/features/board/form.js, client/src/features/board/graphql.js, client/src/features/board/index.js, client/src/features/customer/form.js, client/src/features/customer/index.js, client/src/features/product/form.js, client/src/features/product/index.js, client/src/features/user/index.js, client/src/features/user/personal.js, client/yarn.lock, server/package-lock.json, server/package.json, server/src/models/board.js, server/src/resolver/board.js, server/src/schema/board.js, server/yarn.lock
=> Layout fix

server/config/seed.js, server/index.js, server/src/resolver/customer.js, server/src/schema/board.js
resolves #133
Polo adds the missing fields.
use https://mockaroo.com/ to generate fake data.
=> create seed data

client/src/components/crudTemplate/tableBlock.js, client/src/components/layout/index.js, client/src/features/auth/grapgql.js, client/src/features/auth/login.js, client/src/features/auth/signup.js, client/src/features/board/index.js, client/src/features/customer/index.js, client/src/features/product/index.js, client/src/features/user/graphql.js, client/src/features/user/index.js, server/src/resolver/user.js, server/src/schema/user.js
=> do not show create update and delete button if user is not signed in

README.md, package.json, scripts/travis-after-success.sh
=> update Heroku Docker instructions and scripts

client/index.js, client/package-lock.json, client/package.json, server/index.js, server/package-lock.json, server/package.json
=> add helmet package
